var navbarSupportedContentHtml='';
  navbarSupportedContentHtml += '<ul class="navbar-nav me-auto mb-2 mb-lg-0">';
  navbarSupportedContentHtml += '  <li class="nav-item"><a class="nav-link" href="tokenManagement.html"  >令牌管理</a></li>';
  navbarSupportedContentHtml += '  <li class="nav-item"><a class="nav-link" href="cryptoEvidence.html"  >加密存证</a></li>';
  navbarSupportedContentHtml += '  <li class="nav-item"><a class="nav-link" href="howTo.html">操作手册</a></li>';
  navbarSupportedContentHtml += '  <li class="nav-item"><a class="nav-link" href="utilities.html">区块链工具</a></li>';
  navbarSupportedContentHtml += '  <li class="nav-item"><a class="nav-link" href="search.html"> 防伪查询&#x1F50D;&nbsp;&nbsp;</a></li>';
  navbarSupportedContentHtml += '  <li class="nav-item"><a class="nav-link" href="../en/index.html">ENG</a></li>';
  navbarSupportedContentHtml += '</ul>';

var footerHtml='';
  footerHtml += '<div class="container-fluid" style="font-size:90%">';
  footerHtml +=   '<div class="row">';
  footerHtml +=     '<div class="col-12" style="text-align:center;margin-bottom: 5px;">';
  footerHtml +=       '<a href="https://github.com/ditinow"><img src="../images/logo-github.png" width="25" height="25" alt="github"></a>&nbsp;&nbsp;';
  footerHtml +=       '<a href="index.html"><img src="../images/logo-twitter.png" width="25" height="25" alt="twitter"></a>&nbsp;&nbsp;';
  footerHtml +=       '<a href="index.html"><img src="../images/logo-linkedin.png" width="25" height="25" alt="linkedin"></a>&nbsp;&nbsp;';
  footerHtml +=       '<a href="index.html"><img src="../images/logo-wechat.png" width="25" height="25" alt="wechat"></a>&nbsp;&nbsp;';
  footerHtml +=       '<a href="index.html"><img src="../images/logo-weibo.png" width="25" height="25" alt="weibo"></a>&nbsp;&nbsp;';
  footerHtml +=     '</div>';
  footerHtml +=   '</div>';
  footerHtml +=   '<div class="row" style="text-align:center;background-color:#353A40; color:#fff;">';
  footerHtml +=     '<div class="col-12 col-sm-12 col-md-6 col-lg-4">&#169;2021 DiTiNOW LLC</div>';
  footerHtml +=     '<div class="col-12 col-sm-12 col-md-6 col-lg-4">捐赠 ARDOR-49CE-CXZZ-3QHW-AH4JK</div>';
  footerHtml +=     '<div class="col-12 col-sm-3 col-md-3 col-lg-4">'
  footerHtml +=       '<span class="spanModal" onclick="aboutUsModal.show()"> 关于我们&nbsp;</span>'
  footerHtml +=       '<span class="spanModal" onclick="contactUsModal.show()"> 联系我们&nbsp;</span>'
  footerHtml +=       '<span class="spanModal" onclick="termModal.show()"> 使用条款&nbsp;</span>'
  footerHtml +=       '<span class="spanModal" onclick="legalModal.show()"> 法律声明</span>'
  footerHtml +=     '</div>';
  footerHtml +=   '</div>';
  footerHtml += '</div>';

var footerModal ='<div name="Modal - About Us">';
   footerModal +='  <div class="modal fade" id="aboutUsModal" tabindex="-1" aria-labelledby="aboutUsModalLabel" aria-hidden="true">';
   footerModal +='    <div class="modal-dialog">';
   footerModal +='      <div class="modal-content">';
   footerModal +='        <div class="modal-header">';
   footerModal +='          <h5 class="modal-title" id="aboutUsleModalLabel">关于我们</h5>';
   footerModal +='          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>';
   footerModal +='        </div>';
   footerModal +='        <div class="modal-body">';
   footerModal +='          <p>coming soon ...</p>';
   footerModal +='        </div>';
   footerModal +='        <div class="modal-footer">';
   footerModal +='          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">关闭</button>';
   footerModal +='        </div>';
   footerModal +='      </div>';
   footerModal +='    </div>';
   footerModal +='  </div>';
   footerModal +='</div>';
   footerModal +='<div name="Modal - Contact Us">';
   footerModal +='  <div class="modal fade" id="contactUsModal" tabindex="-1" aria-labelledby="contactUsModalLabel" aria-hidden="true">';
   footerModal +='    <div class="modal-dialog">';
   footerModal +='      <div class="modal-content">';
   footerModal +='        <div class="modal-header">';
   footerModal +='          <h5 class="modal-title" id="contactUsModalLabel">联系我们</h5>';
   footerModal +='          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>';
   footerModal +='        </div>';
   footerModal +='        <div class="modal-body">';
   footerModal +='          <p>coming soon ...</p>';
   footerModal +='        </div>';
   footerModal +='        <div class="modal-footer">';
   footerModal +='          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">关闭</button>';
   footerModal +='        </div>';
   footerModal +='      </div>';
   footerModal +='    </div>';
   footerModal +='  </div>';
   footerModal +='</div>';
   footerModal +='<div name="Modal - Term">';
   footerModal +='  <div class="modal fade" id="termModal" tabindex="-1" aria-labelledby="termModalLabel" aria-hidden="true">';
   footerModal +='    <div class="modal-dialog">';
   footerModal +='      <div class="modal-content">';
   footerModal +='        <div class="modal-header">';
   footerModal +='          <h5 class="modal-title" id="termModalLabel">使用条款</h5>';
   footerModal +='          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>';
   footerModal +='        </div>';
   footerModal +='        <div class="modal-body">';
   footerModal +='          <p>coming soon ...</p>';
   footerModal +='        </div>';
   footerModal +='        <div class="modal-footer">';
   footerModal +='          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">关闭</button>';
   footerModal +='        </div>';
   footerModal +='      </div>';
   footerModal +='    </div>';
   footerModal +='  </div>';
   footerModal +='</div>';
   footerModal +='<div name="Modal - Legal">';
   footerModal +='  <div class="modal fade" id="legalModal" tabindex="-1" aria-labelledby="legalModalLabel" aria-hidden="true">';
   footerModal +='    <div class="modal-dialog">';
   footerModal +='      <div class="modal-content">';
   footerModal +='        <div class="modal-header">';
   footerModal +='          <h5 class="modal-title" id="legalModalLabel">法律声明</h5>';
   footerModal +='          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>';
   footerModal +='        </div>';
   footerModal +='        <div class="modal-body">';
   footerModal +='          <p>coming soon ...</p>';
   footerModal +='        </div>';
   footerModal +='        <div class="modal-footer">';
   footerModal +='           <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">关闭</button>';
   footerModal +='        </div>';
   footerModal +='      </div>';
   footerModal +='    </div>';
   footerModal +='  </div>';
   footerModal +='</div>';
